# typed: false
# frozen_string_literal: true

# This file is generated by scripts/generate-homebrew-formula.sh on each release.
# Do not edit by hand; edit the template at packaging/homebrew/deptrust.rb.tmpl instead.
class Deptrust < Formula
  desc "Local package vulnerability checker and MCP server for AI agents"
  homepage "https://github.com/clidey/deptrust"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.7.0/deptrust_v0.7.0_darwin_arm64.tar.gz"
      sha256 "464e34d97243e39728ceeaaf4abd1924ef8386126dc85e2416fc2b0c4bacd21e"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.7.0/deptrust_v0.7.0_darwin_amd64.tar.gz"
      sha256 "87469365af144e6706249a4459f71b1705ee4551efd5d1c1f08184c9fbd48774"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.7.0/deptrust_v0.7.0_linux_arm64.tar.gz"
      sha256 "6cfbe2ee4038a8b73cc487099496105a667895a3eba65bfe664ed7b42ab7b215"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.7.0/deptrust_v0.7.0_linux_amd64.tar.gz"
      sha256 "96c0c8f1bb8ba460b998ae31f2b73af3c4429ef4dd08634bedfbefc00733d8ed"
    end
  end

  def install
    bin.install "deptrust"
  end

  test do
    # The release binary stamps its version as the git tag, e.g. "deptrust v0.6.0".
    assert_match "deptrust v#{version}", shell_output("#{bin}/deptrust version")
  end
end
