# typed: false
# frozen_string_literal: true

# This file is generated by scripts/generate-homebrew-formula.sh on each release.
# Do not edit by hand; edit the template at packaging/homebrew/deptrust.rb.tmpl instead.
class Deptrust < Formula
  desc "Local package vulnerability checker and MCP server for AI agents"
  homepage "https://github.com/clidey/deptrust"
  version "0.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.11.0/deptrust_v0.11.0_darwin_arm64.tar.gz"
      sha256 "a2720f6f3fcdaf0c25581956c3411fca89f1959427b5246575827da358ed4b8e"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.11.0/deptrust_v0.11.0_darwin_amd64.tar.gz"
      sha256 "7d7afedc5286a03e708654954ee412134167a77e663098bb79de66ac3c8970fc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.11.0/deptrust_v0.11.0_linux_arm64.tar.gz"
      sha256 "8e34751fb1794433ba22e9e2466c9d4095f77220b2e38e5f85d8359f592090af"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.11.0/deptrust_v0.11.0_linux_amd64.tar.gz"
      sha256 "49be177172c17a3e6e1a984e4208f3c58b6d0ad707c1f00fc51f711e2f6b5f45"
    end
  end

  def install
    bin.install "deptrust"
  end

  test do
    # The release binary stamps its version as the git tag, e.g. "deptrust v0.6.0".
    assert_match "deptrust v#{version}", shell_output("#{bin}/deptrust version")
  end
end
