# typed: false
# frozen_string_literal: true

# This file is generated by scripts/generate-homebrew-formula.sh on each release.
# Do not edit by hand; edit the template at packaging/homebrew/deptrust.rb.tmpl instead.
class Deptrust < Formula
  desc "Local package vulnerability checker and MCP server for AI agents"
  homepage "https://github.com/clidey/deptrust"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.10.0/deptrust_v0.10.0_darwin_arm64.tar.gz"
      sha256 "2b699a3e97142ff0cc27736771719ac60fb21bc6ab64b2661a50898e8571b273"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.10.0/deptrust_v0.10.0_darwin_amd64.tar.gz"
      sha256 "b914215f4399cf53c42cef4599f07472fc81689b6fbf969baf2463ede6282e1e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/clidey/deptrust/releases/download/v0.10.0/deptrust_v0.10.0_linux_arm64.tar.gz"
      sha256 "1116c1cce992e8a98ab4f10ae3e2378d0bda52100469546b81ef56d670edf625"
    end
    on_intel do
      url "https://github.com/clidey/deptrust/releases/download/v0.10.0/deptrust_v0.10.0_linux_amd64.tar.gz"
      sha256 "cc51f936caf767f2dc262156980612c644b863814caa949d249f52d20e7ad235"
    end
  end

  def install
    bin.install "deptrust"
  end

  test do
    # The release binary stamps its version as the git tag, e.g. "deptrust v0.6.0".
    assert_match "deptrust v#{version}", shell_output("#{bin}/deptrust version")
  end
end
